name : "jeremyvlegros"
theme : minima
highlighter: rouge

kramdown:
  syntax_highlighter: rouge

Markdown:
  syntax_highlighter: rouge


social_links :

  link :
    name : "GitHub"
    url  : "https://github.com/jeremyvlegros"

  link :
    name : "LinkedIn"
    url  : "https://www.linkedin.com/in/jeremyvlegros/"

  link :
    name : "Twitter"
    url  : "http://twitter.com/jeremyvlegros"

  link :
    name : "Tumblr"
    url  : "https://jeremyvlegros.tumblr.com/"

  link :
    name : "Nexus Mods"
    url  : "https://www.nexusmods.com/users/152566508"

  link :
    name : "Steam"
    url  : "https://steamcommunity.com/id/jeremyvlegros"

  link :
    name : "Twitch"
    url  : "https://www.twitch.tv/jeremyvlegros"

  link :
    name : "Reddit"
    url  : "https://www.reddit.com/user/jeremyvlegros"


test_list :
- "a"
- "b"
- "c"



#date 2023-06-19 0804 1687147473516920743 GMT
