name : "website"

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

permalink: /:categories/:year/:month/:day/:title:output_ext

image_color_linkedin   : "https://i.imgur.com/YcyRAPo.png"
image_color_github     : "https://i.imgur.com/yZCCWuO.png"
image_color_tumblr     : "https://i.imgur.com/w7tOHCU.png"
image_color_twitch     : "https://i.imgur.com/8l1ScN0.png"
image_color_twitter    : "https://i.imgur.com/zopOHUj.png"
image_color_nexus_mods : "https://i.imgur.com/cH3sRB1.png"

social_links :

  github :
    name : "GitHub"
    url  : "https://github.com/jeremyvlegros"

  linkedin :
    name : "LinkedIn"
    url  : "https://www.linkedin.com/in/jeremyvlegros/"

  twitter :
    name : "Twitter"
    url  : "http://twitter.com/jeremyvlegros"

  tumblr :
    name : "Tumblr"
    url  : "https://jeremyvlegros.tumblr.com/"

  nexus_mods :
    name : "Nexus Mods"
    url  : "https://www.nexusmods.com/users/152566508"

  steam :
    name : "Steam"
    url  : "https://steamcommunity.com/id/jeremyvlegros"

  twitch :
    name : "Twitch"
    url  : "https://www.twitch.tv/jeremyvlegros"

  reddit :
    name : "Reddit"
    url  : "https://www.reddit.com/user/jeremyvlegros"





