#date 2023-06-29 14:48 1688035736373107839 GMT

name : "website"
theme : minima
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

permalink: /:categories/:year/:month/:day/:title:output_ext

image_color_linkedin   : "https://i.imgur.com/YcyRAPo.png"
image_color_github     : "https://i.imgur.com/yZCCWuO.png"
image_color_tumblr     : "https://i.imgur.com/w7tOHCU.png"
image_color_twitch     : "https://i.imgur.com/8l1ScN0.png"
image_color_twitter    : "https://i.imgur.com/zopOHUj.png"
image_color_nexus_mods : "https://i.imgur.com/cH3sRB1.png"

image_color_1  : "https://i.imgur.com/BpwYECq.png"
image_color_2  : "https://i.imgur.com/UNPogEC.png"
image_color_3  : "https://i.imgur.com/WeQ9pUI.png"
image_color_4  : "https://i.imgur.com/rwMJzJY.png"
image_color_5  : "https://i.imgur.com/y4GOWP8.png"
image_color_6  : "https://i.imgur.com/XmCbs0H.png"
image_color_7  : "https://i.imgur.com/Oc2vg4j.png"
image_color_8  : "https://i.imgur.com/1LxHBZo.png"
image_color_9  : "https://i.imgur.com/A74C7te.png"
image_color_10 : "https://i.imgur.com/ld3Y0ZH.png"
image_color_11 : "https://i.imgur.com/vE1poN2.png"
image_color_12 : "https://i.imgur.com/6H0pWyd.png"
image_color_13 : "https://i.imgur.com/H426FqL.png"
image_color_14 : "https://i.imgur.com/rvT3aBX.png"
image_color_15 : "https://i.imgur.com/NzqdErY.png"
image_color_16 : "https://i.imgur.com/XRItiBv.png"
image_color_17 : "https://i.imgur.com/EFiyrR0.png"
image_color_18 : "https://i.imgur.com/HlEsCy0.png"
image_color_19 : "https://i.imgur.com/NoDA2YL.png"
image_color_20 : "https://i.imgur.com/LZTjWOv.png"
image_color_21 : "https://i.imgur.com/t4trRjd.png"
image_color_22 : "https://i.imgur.com/PWIooMi.png"
image_color_23 : "https://i.imgur.com/Sp0JMH7.png"
image_color_24 : "https://i.imgur.com/iyKhqH3.png"
image_color_25 : "https://i.imgur.com/dSz3lXU.png"
image_color_26 : "https://i.imgur.com/1S9qN2X.png"
image_color_27 : "https://i.imgur.com/C3KnBzl.png"
image_color_28 : "https://i.imgur.com/kPf02Ou.png"
image_color_29 : "https://i.imgur.com/uDvk9ZQ.png"
image_color_30 : "https://i.imgur.com/GomogEH.png"
image_color_31 : "https://i.imgur.com/0VgppgF.png"



social_links :

  github :
    name : "GitHub"
    url  : "https://github.com/jeremyvlegros"

  linkedin :
    name : "LinkedIn"
    url  : "https://www.linkedin.com/in/jeremyvlegros/"

  twitter :
    name : "Twitter"
    url  : "http://twitter.com/jeremyvlegros"

  tumblr :
    name : "Tumblr"
    url  : "https://jeremyvlegros.tumblr.com/"

  nexus_mods :
    name : "Nexus Mods"
    url  : "https://www.nexusmods.com/users/152566508"

  steam :
    name : "Steam"
    url  : "https://steamcommunity.com/id/jeremyvlegros"

  twitch :
    name : "Twitch"
    url  : "https://www.twitch.tv/jeremyvlegros"

  reddit :
    name : "Reddit"
    url  : "https://www.reddit.com/user/jeremyvlegros"
