name : "website"

collections:
  tag :
    output: true
    permalink : /tag/:path

defaults :
  - scope:
      path: ""
      type : "posts"
    values:
      layout: "post_layout"
      category: "post"
  - scope:
      path: ""
      type: "tag"
    values:
      layout: "timeline_layout"

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

ARRAY_EMPTY : []
