name: "jeremyvlegros"

sass:
  style: compressed
  sourcemap: never

collections:
  tag:
    output: true
    permalink: /tag/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "layout_post"
  - scope:
      path: ""
      type: "tag"
    values:
      layout: "layout_timeline"

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

ARRAY_EMPTY: [ ]


