name : "website"
theme : minima
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

permalink: /:categories/:year/:month/:day/:title:output_ext

image_color_linkedin   : "https://i.imgur.com/YcyRAPo.png"
image_color_github     : "https://i.imgur.com/yZCCWuO.png"
image_color_tumblr     : "https://i.imgur.com/w7tOHCU.png"
image_color_twitch     : "https://i.imgur.com/8l1ScN0.png"
image_color_twitter    : "https://i.imgur.com/zopOHUj.png"
image_color_nexus_mods : "https://i.imgur.com/cH3sRB1.png"

string_image_color_urls  : "null,https://i.imgur.com/BpwYECq.png,https://i.imgur.com/UNPogEC.png,https://i.imgur.com/WeQ9pUI.png,https://i.imgur.com/rwMJzJY.png,https://i.imgur.com/y4GOWP8.png,https://i.imgur.com/XmCbs0H.png,https://i.imgur.com/Oc2vg4j.png,https://i.imgur.com/1LxHBZo.png,https://i.imgur.com/A74C7te.png,https://i.imgur.com/ld3Y0ZH.png,https://i.imgur.com/vE1poN2.png,https://i.imgur.com/6H0pWyd.png,https://i.imgur.com/H426FqL.png,https://i.imgur.com/rvT3aBX.png,https://i.imgur.com/NzqdErY.png,https://i.imgur.com/XRItiBv.png,https://i.imgur.com/EFiyrR0.png,https://i.imgur.com/HlEsCy0.png,https://i.imgur.com/NoDA2YL.png,https://i.imgur.com/LZTjWOv.png,https://i.imgur.com/t4trRjd.png,https://i.imgur.com/PWIooMi.png,https://i.imgur.com/Sp0JMH7.png,https://i.imgur.com/iyKhqH3.png,https://i.imgur.com/dSz3lXU.png,https://i.imgur.com/1S9qN2X.png,https://i.imgur.com/C3KnBzl.png,https://i.imgur.com/kPf02Ou.png,https://i.imgur.com/uDvk9ZQ.png,https://i.imgur.com/GomogEH.png,https://i.imgur.com/0VgppgF.png"

social_links :

  github :
    name : "GitHub"
    url  : "https://github.com/jeremyvlegros"

  linkedin :
    name : "LinkedIn"
    url  : "https://www.linkedin.com/in/jeremyvlegros/"

  twitter :
    name : "Twitter"
    url  : "http://twitter.com/jeremyvlegros"

  tumblr :
    name : "Tumblr"
    url  : "https://jeremyvlegros.tumblr.com/"

  nexus_mods :
    name : "Nexus Mods"
    url  : "https://www.nexusmods.com/users/152566508"

  steam :
    name : "Steam"
    url  : "https://steamcommunity.com/id/jeremyvlegros"

  twitch :
    name : "Twitch"
    url  : "https://www.twitch.tv/jeremyvlegros"

  reddit :
    name : "Reddit"
    url  : "https://www.reddit.com/user/jeremyvlegros"





